# Site settings
title: scudo's junkie site

admin: scudo

excerpt_separator: <!--more-->

descript: Hi, this is scudo's website!

url: "https://scudo005.github.io" # update if necessary

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap 