# Site settings
title: scudo's junkie site

author: scudo

excerpt_separator: <!--more-->

description: Tech, art, and more.

url: "https://scudo005.github.io" # update if necessary

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
